package SpellChecker;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;
import DataStructures.GTUHashSet;
import DataStructures.GTUArrayList;
import DataStructures.GTUIterator;

/**
 * An interactive spell checking application that loads a dictionary into a
 * custom hash set and provides real-time word validation with intelligent
 * suggestions for misspelled words.
 *
 * <p>The spell checker operates in an interactive CLI mode where users can
 * type words and receive instant feedback on correctness. For misspelled
 * words, the system generates suggestions using edit distance algorithms
 * (distance 1 and 2) powered by {@link EditDistanceHelper}.</p>
 *
 * <h3>Key Features</h3>
 * <ul>
 *   <li>Dictionary loading from flat text files (one word per line)</li>
 *   <li>O(1) average-case word lookup via custom hash set</li>
 *   <li>JIT warm-up phase for consistent sub-millisecond performance</li>
 *   <li>Real-time performance metrics (lookup time, memory usage, collisions)</li>
 *   <li>Special character support in word validation ({@code @, ., -, !, ?, +})</li>
 * </ul>
 *
 * @author Zehra Güzel
 * @version 1.0
 * @see EditDistanceHelper
 * @see DataStructures.GTUHashSet
 */
public class SpellChecker {
    private GTUHashSet<String> dictionary;

    /**
     * Constructs a new SpellChecker with an empty dictionary.
     */
    public SpellChecker() {
        dictionary = new GTUHashSet<>();
    }

    /**
     * Loads words from a dictionary file into the internal hash set.
     * Each line in the file is treated as a single word entry.
     * All words are converted to lowercase and trimmed of whitespace.
     *
     * @param filepath the path to the dictionary file
     * @throws IOException if the file cannot be read
     */
    public void loadDictionary(String filepath) throws IOException {
        BufferedReader reader = new BufferedReader(new FileReader(filepath));
        String line;
        while ((line = reader.readLine()) != null) {
            dictionary.add(line.trim().toLowerCase());
        }
        reader.close();
    }

    /**
     * Validates whether a word contains acceptable characters.
     *
     * <p>A valid word must contain at least one letter and may only consist
     * of letters, digits, and specific special characters
     * ({@code @, ., -, ,, !, ?, +}).</p>
     *
     * @param word the word to validate
     * @return {@code true} if the word matches the validation pattern
     */
    public boolean isValidWordWithSpecialChars(String word) {
        // The word must contain at least one letter and can only consist of letters, digits, and specific special characters (e.g., @ . - , ? !)
        return word.matches(".*\\p{L}.*") && word.matches("[\\p{L}\\p{N}@\\.\\-\\,\\!?\\+]*");
    }


    /**
     * Checks if a word exists in the dictionary.
     *
     * <p>First validates the word format, then performs a hash-based
     * dictionary lookup in O(1) average time.</p>
     *
     * @param word the word to check
     * @return {@code true} if the word is valid and found in the dictionary
     */
    public boolean checkWord(String word) {
        if (!isValidWordWithSpecialChars(word)) {
            System.out.println("Invalid word. Only letters, digits, and certain special characters (@ . -) are allowed, and the word must contain at least one letter.");
            return false;
        }
        return dictionary.contains(word.toLowerCase()); // Check the word in dictionary
    }

    /**
     * Starts the interactive spell checking session.
     *
     * <p>The user is prompted to enter words one at a time. For each word:
     * <ul>
     *   <li>If correct — displays "Correct."</li>
     *   <li>If misspelled — displays suggestions generated by edit distance</li>
     *   <li>If invalid format — displays validation error</li>
     * </ul>
     * Type {@code exitprogram} to terminate the session.</p>
     */
    public void runInteractive() {
        Scanner scanner = new Scanner(System.in);

        while (true) {
            System.out.print("Enter a word (or type 'exitprogram' to quit): ");
            String input = scanner.nextLine().trim().toLowerCase();

            // Exit condition
            if (input.equals("exitprogram")) {
                System.out.println("Exiting SpellChecker. Goodbye!");
                break;
            }

            long t0 = System.nanoTime();

            // Check if the word is valid or incorrect
            if (checkWord(input)) {
                System.out.println("Correct.");
            } else {
                if (!isValidWordWithSpecialChars(input)) {
                    continue; // Skip suggestion generation for invalid word
                }
                System.out.println("Incorrect.");
                GTUArrayList<String> sugg = EditDistanceHelper.generateSuggestions(input, dictionary);
                System.out.print("Suggestions: ");
                if (sugg.size() == 0) {
                    System.out.println("No suggestions found.");
                } else {
                    for (int i = 0; i < sugg.size(); i++) {
                        System.out.print(sugg.get(i));
                        if (i < sugg.size() - 1) System.out.print(", ");
                    }
                    System.out.println();
                }
            }

            long t1 = System.nanoTime();
            System.out.printf("Lookup and suggestion took %.2f ms%n", (t1 - t0) / 1e6);
        }
    }

    /**
     * Performs a JIT warm-up phase by running lookups and suggestion
     * generation on the first 20 words in the dictionary.
     *
     * <p>This ensures that the JVM's Just-In-Time compiler has optimized
     * the hot paths before user interaction begins, resulting in more
     * consistent and faster response times.</p>
     */
    private void warmUp() {
        int count = 0;
        GTUIterator<String> it = dictionary.keyIterator();
        while (it.hasNext() && count < 20) {
            String word = it.next();
            dictionary.contains(word); // Optimize hash structure for lookup
            EditDistanceHelper.generateSuggestions(word, dictionary); // Optimize edit-distance function for word suggestions
            count++;
        }
    }

    /**
     * Application entry point. Loads the dictionary, displays performance
     * statistics, runs the warm-up phase, and starts the interactive mode.
     *
     * @param args command-line arguments (not used)
     */
    public static void main(String[] args) {
        try {
            SpellChecker checker = new SpellChecker();
            checker.loadDictionary("dictionary.txt");
            System.out.println("Total collisions during dictionary load: " + checker.dictionary.getCollisionCount());

            // Trigger garbage collection to ensure accurate memory usage measurement
            Runtime runtime = Runtime.getRuntime();
            runtime.gc();
            long memoryUsed = runtime.totalMemory() - runtime.freeMemory();
            System.out.printf("Approximate memory used: %.2f MB%n", memoryUsed / (1024.0 * 1024.0));

            checker.warmUp(); // Pre-load the dictionary and optimize the system before user interaction

            checker.runInteractive(); // Start the interactive mode
        } catch (IOException e) {
            System.err.println("Failed to load dictionary: " + e.getMessage());
        }
    }
}